# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5c37e0bdda2687d30f410bf5ed296acdda0f0a628ac33a3a013a5fd56676768c9989936b5ae649f16c375b9e3df39e4344ad3526aaee5eb6693cc1e201c581fb

test:
  secret_key_base: a6b28c34532d1e95a01c04bc8eed0eb6041cea73cbe345d8984a96bc875a622d249075d24cfae935384e3c59f262b03a0059e2f97f7566fa7a66203ffec1d462

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
